export const SESSION_PROMPTS = {
    focus: [
        "Brainstorm An Idea",
        "Make A Decision",
        "Solve A Challenge",
        "Reflect On Something That Happened",
        "Plan Next Steps",
    ],
    area: [
        "Customer Experience",
        "Data",
        "Finance",
        "Leadership",
        "Marketing",
        "Operations",
        "Product/Service Design",
        "Project Development/Management",
        "Risk & Compliance",
        "Strategy/Vision",
        "Sustainability/Social Impact",
        "Team/People",
        "Technology",
    ],
    feeling: [
        "Anxious",
        "Overwhelmed",
        "Uncertain",
        "Stuck",
        "Neutral",
        "Curious",
        "Focused",
        "Steady",
        "Energized",
        "Inspired",
        "I'm Not Sure",
        "I'm All Over The Place",
    ],
    outcome: [
        "Clarity",
        "A Decision",
        "A New Perspective",
        "An Action Plan",
        "Relief or Confidence",
        "I'm Not Sure Yet - Help Me Explore",
    ],
} as const;
